
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Oct 18 02:15:55 CEST 2003
//----------------------------------------------------

package tum.umlsec.viki.tools.dynaviki.model.scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPCALL = 14;
  public static final int ELSE = 21;
  public static final int PUBLICKEYOF = 5;
  public static final int EQUAL = 12;
  public static final int NONCEOF = 8;
  public static final int NOTEQUAL = 13;
  public static final int APPLYKEY = 2;
  public static final int IDENTIFIER = 9;
  public static final int CONCAT = 20;
  public static final int RPARSQUARE = 19;
  public static final int LPARSQUARE = 18;
  public static final int THIS = 3;
  public static final int SENDEROF = 4;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int INTNUMBER = 10;
  public static final int ASSIGN = 11;
  public static final int RPAR = 17;
  public static final int SYMMETRICKEYOF = 7;
  public static final int LPAR = 16;
  public static final int SECRETKEYOF = 6;
}

