/*
 * Generated by classgen, version 1.3
 * 15/01/04 14:52
 */
package tum.umlsec.viki.tools.dynaviki.model.scanner;

public abstract class USE_ParameterList extends USE_BASE implements SyntaxNode {

  private SyntaxNode parent;

  public USE_RTerm getParam() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setParam(USE_RTerm param) {
    throw new ClassCastException("tried to call abstract method");
  }

  public USE_ParameterList getParamList() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setParamList(USE_ParameterList paramList) {
    throw new ClassCastException("tried to call abstract method");
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
