/*
 * Generated by classgen, version 1.3
 * 15/01/04 14:52
 */
package tum.umlsec.viki.tools.dynaviki.model.scanner;

public class USE_SenderOf extends USE_RTerm {

  private USE_Variable variable;

  public USE_SenderOf (USE_Variable variable) {
    this.variable = variable;
    if (variable != null) variable.setParent(this);
  }

  public USE_Variable getVariable() {
    return variable;
  }

  public void setVariable(USE_Variable variable) {
    this.variable = variable;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (variable != null) variable.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (variable != null) variable.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (variable != null) variable.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("USE_SenderOf(\n");
      if (variable != null)
        buffer.append(variable.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [USE_SenderOf]");
    return buffer.toString();
  }
}
