/*
 * Generated by classgen, version 1.3
 * 15/01/04 14:52
 */

package tum.umlsec.viki.tools.dynaviki.model.scanner;

public interface SyntaxNode {

  public void accept(Visitor visitor);

  public void childrenAccept(Visitor visitor);
  public void traverseBottomUp(Visitor visitor);
  public void traverseTopDown(Visitor visitor);

  public SyntaxNode getParent();
  public void setParent(SyntaxNode parent);
}
