/*
 * Generated by classgen, version 1.3
 * 15/01/04 14:52
 */
package tum.umlsec.viki.tools.dynaviki.model.scanner;

public abstract class USE_GuardVirt extends USE_BASE implements SyntaxNode {

  private SyntaxNode parent;

  public USE_RTerm getLTerm() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setLTerm(USE_RTerm lTerm) {
    throw new ClassCastException("tried to call abstract method");
  }

  public USE_CompareOperator getOp() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setOp(USE_CompareOperator op) {
    throw new ClassCastException("tried to call abstract method");
  }

  public USE_RTerm getRTerm() {
    throw new ClassCastException("tried to call abstract method");
  }

  public void setRTerm(USE_RTerm rTerm) {
    throw new ClassCastException("tried to call abstract method");
  }

  public SyntaxNode getParent() {
    return parent;
  }

  public void setParent(SyntaxNode parent) {
    this.parent = parent;
  }

  public abstract void accept(Visitor visitor);
  public abstract void childrenAccept(Visitor visitor);
  public abstract void traverseTopDown(Visitor visitor);
  public abstract void traverseBottomUp(Visitor visitor);
  public String toString() {
    return toString("");
  }

  public abstract String toString(String tab);
}
