# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant-provision-reboot-plugin'

Vagrant.configure(2) do |config|

  # This VM use windows7 with IE 11 box provided by Microsoft.
  config.vm.box = "modernIE/w7-ie11"
  config.vm.hostname = "UMLsec"
  config.vm.provider :virtualbox do |vb|
    vb.name = "UMLsec"
  end  

  
  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Share folders to the guest VM.
  config.vm.synced_folder "../", "/vagrant_UMLsec"
  

  # configuration of VM
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "512"
  #	  # Disable USB 2.0 
     vb.customize ["modifyvm", :id, "--usb", "off"] 
     vb.customize ["modifyvm", :id, "--usbehci", "off"] 
	 
  end
  

  # execute provision shells to set additional configuration for the VM
  config.vm.provision :shell, path: "installScript/disable-UAC.ps1"
  config.vm.provision :windows_reboot
  config.vm.provision :shell, path: "installScript/Install-JRE.ps1"
  config.vm.provision :windows_reboot
  config.vm.provision :shell, path: "installScript/message.ps1"  

  
end
