/* Generated by Together */

package tum.umlsec.viki.tools.dynaviki;

import tum.umlsec.viki.framework.mdr.IMdrContainer;
import tum.umlsec.viki.framework.toolbase.IVikiToolBase;
import tum.umlsec.viki.framework.toolbase.IVikiToolConsole;
import tum.umlsec.viki.framework.toolbase.IVikiToolGui;
import tum.umlsec.viki.framework.toolbase.IVikiToolWeb;

public class VikiToolDynamic implements IVikiToolBase {
	public IVikiToolConsole getConsole() {
		if(consoleClass == null) {		
			consoleClass = new DynaVikiConsole(this);  
		}
		return consoleClass;	
	}
	public IVikiToolGui getGui() {
		if(guiClass == null) {				
			guiClass = new DynaVikiGui(this);
		}
		return guiClass;	
	}
	public IVikiToolWeb getWeb() { return null; }


	public void initialiseBase(IMdrContainer _mdrContainer) {
		mdrContainer = _mdrContainer;
	}
	
	public String getToolName() {				return "Statechart Crypto Model-Checker";							}
	public String getToolDescription() {		return "Verifies dynamic properties of the model";	}
	public IMdrContainer getMdrContainer() {	return mdrContainer;								}


	DynaVikiGui guiClass = null;
	DynaVikiConsole consoleClass = null; 
	IMdrContainer mdrContainer;
}
