/*
 * Generated by classgen, version 1.3
 * 15/01/04 14:52
 */
package tum.umlsec.viki.tools.dynaviki.model.scanner;

public class USE_ParameterListEnd extends USE_ParameterList {

  private USE_RTerm param;

  public USE_ParameterListEnd (USE_RTerm param) {
    this.param = param;
    if (param != null) param.setParent(this);
  }

  public USE_RTerm getParam() {
    return param;
  }

  public void setParam(USE_RTerm param) {
    this.param = param;
  }

  public void accept(Visitor visitor) {
    visitor.visit(this);
  }

  public void childrenAccept(Visitor visitor) {
    if (param != null) param.accept(visitor);
  }

  public void traverseTopDown(Visitor visitor) {
    accept(visitor);
    if (param != null) param.traverseTopDown(visitor);
  }

  public void traverseBottomUp(Visitor visitor) {
    if (param != null) param.traverseBottomUp(visitor);
    accept(visitor);
  }

  public String toString(String tab) {
    StringBuffer buffer = new StringBuffer();
    buffer.append(tab);
    buffer.append("USE_ParameterListEnd(\n");
      if (param != null)
        buffer.append(param.toString("  "+tab));
      else
        buffer.append(tab+"  null");
    buffer.append("\n");
    buffer.append(tab);
    buffer.append(") [USE_ParameterListEnd]");
    return buffer.toString();
  }
}
